### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by aytaa** [itzpradip/react-navigation-v5-mix#4]
How can i pass data to drawer (username)

**Comment by AmarnathGangapuram** [comment]
Create one more context **AuthContextState** and follow below code and get username from asyncStorage then send it to dispatch then it's working fine but I am also suffered for getting userName with single Context. I am also a beginner to Hooks so I am not sure it is the correct way or not

 in useEffect App.js
`useEffect(() => {
    setTimeout(async() => {
      // setIsLoading(false);
      let userToken,userName;
      userToken = null;
      userName=null;
      try {
        userToken = await AsyncStorage.getItem('userToken');
        userName = await AsyncStorage.getItem('userName');
      } catch(e) {
        console.log(e);
      }
      // console.log('user tokens: ', userToken);
      dispatch({ type: 'RETRIEVE_TOKEN', id: userName,token: userToken });
    }, 1000);
  }, []);`

` <PaperProvider theme={theme}>
    <AuthContext.Provider value={authContext}>
    <AuthContextState.Provider value={[loginState]}>
    <NavigationContainer theme={theme} >
      { loginState.userToken !== null ? (
        <Drawer.Navigator drawerContent={props => <DrawerContent {...props} />}>
          <Drawer.Screen name="HomeDrawer" component={MainTabScreen} />
          <Drawer.Screen name="SupportScreen" component={SupportScreen} />
          <Drawer.Screen name="SettingsScreen" component={SettingsScreen} />
          <Drawer.Screen name="BookmarkScreen" component={BookmarkScreen} />
        </Drawer.Navigator>
      )
    :
      <RootStackScreen/>
    }
    </NavigationContainer>
    </AuthContextState.Provider>
    </AuthContext.Provider>
    </PaperProvider>`

Get username in where in the project : 

`import { AuthContextState } from '../components/context';
const [loginState]=React.useContext(AuthContextState)
 console.log(loginState.userName)`

**Comment by aytaa** [comment]
thank you very much !
